/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autoBooker;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;

public class App {
    public static void book(String e, String p) {

        // create WebDriver obj "driver" and set to ChromeDriver
        WebDriver driver = new ChromeDriver();

        // maximize the window
        driver.manage().window().maximize();

        // request ChromeDriver to request HTTP for golf website
        driver.get("https://city-of-london-golf-courses.book.teeitup.golf/login");

        // create By object and get the username element on login
        By usernameBy = By.id("txtUsername");

        // wait setting of max 15 s to hold for pull up delay
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        wait.until(ExpectedConditions.presenceOfElementLocated(usernameBy));

        // driver finds username and password element and sends email and password
        driver.findElement(usernameBy).sendKeys(e);
        driver.findElement(By.id("txtPassword")).sendKeys(p);

        // create button object for the button element and find by the className and click
        WebElement lgnButton = driver.findElement(By.className("MuiButton-label"));
        lgnButton.click();

        // to get the next week date
        Calendar calendar = Calendar.getInstance();
        Date currentDate = calendar.getTime();

        calendar.add(Calendar.DAY_OF_WEEK, 7);
        Date nextWeekDate = calendar.getTime();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String nextWeekFormattedDate = dateFormat.format(nextWeekDate);

        By userLoggedIn = By.xpath("//button[@data-testid='core-user-profile']");

        wait.until(ExpectedConditions.presenceOfElementLocated(userLoggedIn));

        // get the website with all the appropriate settings (9 AM - 11 AM, 3-4 golfers, next week)
        driver.get("https://city-of-london-golf-courses.book.teeitup.golf/?course=9710&date=" + nextWeekDate + "&end=20&golfers=3,4&holes=18&start=09");

        By bookNowClassName = By.xpath("//button[@data-testid='teetimes_book_now_button']");

        wait.until(ExpectedConditions.presenceOfElementLocated(bookNowClassName));
        WebElement bookButton = driver.findElement(bookNowClassName);

        bookButton.click();

        driver.quit();
    }


    public static void main(String[] args) {

        String[] email = {"g.nahan75@gmail.com", "ginahan@hotmail.com"};
        String[] password = {"ar1eth2ac"};

        for (int i = 0; i < 1; i++) {
            book(email[i], password[0]);

        }

    }
}
