/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autoBooker;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class App {
    public static void book(String e, String p) {
        WebDriver driver = new ChromeDriver();

        driver.get("https://city-of-london-golf-courses.book.teeitup.golf/login");
        driver.findElement(By.id("txtUsername1")).sendKeys(e);
        driver.findElement(By.id("txtPassword1")).sendKeys(p);

        driver.quit();
    }

    public static void main(String[] args) {

        String[] email = {"g.nahan", "gina"};
        String[] password = {"ar1"};

        for (int i = 0; i < 1; i++) {
            book(email[i], password[0]);

        }

    }
}
