/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autoBooker;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void book() {
    }
}
